import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import NotFound from "@/pages/NotFound";
import { Route, Switch } from "wouter";
import ErrorBoundary from "./components/ErrorBoundary";
import { ThemeProvider } from "./contexts/ThemeContext";
import { useMobile } from "./hooks/useMobile";
import { BottomNavigation } from "./components/BottomNavigation";
import { MobileDashboard } from "./components/MobileDashboard";
import Home from "./pages/Home";
import AceitarConvite from "./pages/AceitarConvite";
import Pagamentos from "./pages/Pagamentos";
import Recebimentos from "./pages/Recebimentos";
import Relatorios from "./pages/Relatorios";
import Guia from "./pages/Guia";
import Faq from "./pages/Faq";
import Usuarios from "./pages/Usuarios";
import Configuracoes from "./pages/Configuracoes";
import Clientes from "./pages/Clientes";
import ClienteDetalhado from "./pages/Clie
